$ cat kafkaworking.yaml
apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: confluent
spec:
  replicas: 1
  image:
    application: confluentinc/cp-server:7.9.0
    init: confluentinc/confluent-init-container:2.11.0
  dataVolumeCapacity: "10Gi"
  podTemplate:
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 1
        memory: 2Gi
  configOverrides:
    server:
      - node.id=1
      - broker.id=1
      - cluster.id=MTliMWNjYTYtMTMyZS00Mw
      - process.roles=broker
      - listener.security.protocol.map=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT
      - listeners=PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092,INTERNAL://0.0.0.0:9071
      - advertised.listeners=PLAINTEXT://kafka-0.kafka.confluent.svc.cluster.local:29092,PLAINTEXT_HOST://kafka.confluent.svc.cluster.local:9092,INTERNAL://kafka.confluent.svc.cluster.local:9071
      #- bootstrap.servers=kcontroller-0.kcontroller.confluent.svc.cluster.local:29093
      - offsets.topic.replication.factor=1
      - group.initial.rebalance.delay.ms=0
      - transaction.state.log.min.isr=1
      - transaction.state.log.replication.factor=1
      - inter.broker.listener.name=PLAINTEXT
      - log.dirs=/var/lib/kafka/data
      - kraft.controller.reconnect.backoff.ms=5000
      - kraft.controller.reconnect.backoff.max.ms=30000
      - controller.socket.timeout.ms=60000
      - controller.quorum.request.timeout.ms=60000

gavva@Pullaiah-laptop MINGW64 ~/confluent-kafka/confluent-for-kubernetes-latest-20250220/confluent-operator
$

gavva@Pullaiah-laptop MINGW64 ~/confluent-kafka/confluent-for-kubernetes-latest-20250220/confluent-operator
$ cat kraftworking.yaml
apiVersion: platform.confluent.io/v1beta1
kind: KRaftController
metadata:
  name: kcontroller
  namespace: confluent
spec:
  replicas: 1
  image:
    application: confluentinc/cp-server:7.9.0
    init: confluentinc/confluent-init-container:2.11.0
  dataVolumeCapacity: "10Gi"
  podTemplate:
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 1
        memory: 2Gi
  configOverrides:
    server:
      - process.roles=controller
      - node.id=0
      - broker.id=0
      - controller.listener.names=CONTROLLER,PLAINTEXT
      - listeners=CONTROLLER://0.0.0.0:29093,PLAINTEXT://0.0.0.0:9074
      - advertised.listeners=CONTROLLER://kcontroller-0.kcontroller.confluent.svc.cluster.local:29093,PLAINTEXT://kcontroller-0.kcontroller.confluent.svc.cluster.local:9074
      - listener.security.protocol.map=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,REPLICATION:PLAINTEXT
      - controller.quorum.voters=0@kcontroller-0.kcontroller.confluent.svc.cluster.local:29093
      - log.dirs=/var/lib/kafka/data
      - cluster.id=MkU3OEVBNTcwNTJENDM2Qk
